#! /bin/sh
feh --bg-fill ~/Pictures/chungus.jpg &
polybar bspwm &
picom &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9
bspc config border_width         2
bspc config window_gap          10
bspc normal_border_color #f00
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#eceff4"
bspc config normal_border_color "#2e3440"
while pgrep -u $UID -f bspwm_window_titles >/dev/null; do pkill -f bspwm_window_titles; done
# bspwm_window_titles &
bspc rule -a Pavucontrol state=floating floating=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
